//! The release PIPELINE drill: manifests minted by the real `wayland-release`
//! binary, using the exact command pair `.github/workflows/release.yml` runs,
//! driven through the real shipped `ReleaseVerifier` and `decide_update`.
//!
//! ## Why this exists next to `self_update_trust.rs` rather than inside it
//!
//! That file proves the DECISION is right, using a library harness to mint its
//! corpus. This file proves the two halves MEET: that bytes produced by the
//! command line `release.yml` actually runs are bytes the shipped binary
//! accepts. Those are different claims, and only the second one catches a
//! manifest-schema drift between `wcore-eval-scenarios` and `wcore-cli`, a
//! `--key-id` that does not match the trust root, an asset filename that misses
//! `RELEASE_MANIFEST_ASSET_SUFFIX`, or a `manifest-sign` invocation whose seed
//! never reached stdin.
//!
//! A near-miss on any of those fails SILENTLY in production: `self-update`
//! simply reports that the release publishes no manifest, and refuses. Green
//! release run, broken updater, no error anywhere.
//!
//! ## How it is driven, and why it cannot self-pass
//!
//! `.github/scripts/release-manifest-drill.sh` builds `wayland-release`, mints
//! a corpus of signed manifests with THROWAWAY keys generated at run time, and
//! runs these tests with `WAYLAND_RELEASE_PIPELINE_CORPUS` pointing at it.
//!
//! Three self-passing modes are closed deliberately:
//!
//! - **No early return.** A missing or incomplete corpus PANICS with the
//!   command to produce it. It never returns quietly, because an env-gated
//!   early `return` is how `live_integrity.rs` printed `5 passed` for zero
//!   work.
//! - **The pass count is asserted by the driver**, not inferred from an exit
//!   status, because a suite of `#[ignore]`d tests exits 0 having run none.
//! - **Every refusal is paired with an ACCEPTED control in the same test.** A
//!   corpus of only rejections passes trivially against a verifier that refuses
//!   everything — which would brick every legitimate update while looking
//!   green.
//!
//! ## No credential, ever
//!
//! Every key is generated by `wayland-release trust-root-init` into a temporary
//! directory that the driver deletes. No real seed is read, printed or written,
//! and this file contains no key material.

#![cfg(unix)]

use std::path::{Path, PathBuf};

use wcore_cli::self_update::update_trust::{
    DEFAULT_MAX_MANIFEST_AGE_SECS, FreezeState, RELEASE_MANIFEST_ASSET_SUFFIX, ReleaseVerifier,
    UpdateDecision, UpdateOffer, UpdateTrustError, VerifiedManifest,
};

/// Written by the driver so the drill is deterministic: the same `now` the
/// manifests were minted against, and the versions they describe.
#[derive(serde::Deserialize)]
struct DrillParameters {
    now_unix: u64,
    running_version: String,
    newer_version: String,
    older_version: String,
    control_sequence: u64,
}

struct Corpus {
    root: PathBuf,
    parameters: DrillParameters,
}

impl Corpus {
    /// PANICS when the corpus is absent. Never returns quietly — that is the
    /// self-passing mode this file is built to avoid.
    fn load() -> Self {
        let root = std::env::var("WAYLAND_RELEASE_PIPELINE_CORPUS").unwrap_or_else(|_| {
            panic!(
                "WAYLAND_RELEASE_PIPELINE_CORPUS is not set. This drill verifies artifacts minted \
                 by the real `wayland-release` binary and cannot be run bare. Produce them with:\n\
                 \n    .github/scripts/release-manifest-drill.sh\n"
            )
        });
        let root = PathBuf::from(root);
        assert!(
            root.is_dir(),
            "corpus directory {} does not exist",
            root.display()
        );

        let parameters_path = root.join("drill-parameters.json");
        let parameters: DrillParameters = serde_json::from_slice(
            &std::fs::read(&parameters_path)
                .unwrap_or_else(|error| panic!("{}: {error}", parameters_path.display())),
        )
        .expect("drill-parameters.json must parse");

        Self { root, parameters }
    }

    fn bytes(&self, name: &str) -> Vec<u8> {
        let path = self.root.join(name);
        std::fs::read(&path).unwrap_or_else(|error| {
            panic!(
                "{} is missing from the corpus ({error}). The driver mints every case; a missing \
                 file means a `wayland-release` invocation failed and was not caught.",
                path.display()
            )
        })
    }

    /// The trust root the driver minted, read through the SHIPPED constructor.
    fn verifier(&self, trust_root: &str) -> ReleaseVerifier {
        ReleaseVerifier::with_trust_root_json(&self.bytes(trust_root))
            .expect("a trust root minted by `wayland-release trust-root-init` must be accepted")
    }

    fn now(&self) -> u64 {
        self.parameters.now_unix
    }

    /// The pristine control, re-verified from disk. Every test calls this
    /// before asserting a refusal, so no test can pass against a verifier that
    /// refuses everything.
    fn control(&self, verifier: &ReleaseVerifier) -> VerifiedManifest {
        let manifest = verifier
            .verify_manifest_json(&self.bytes(&control_asset()), self.now())
            .expect("CONTROL: the pristine CLI-minted manifest must verify");
        let state = FreezeState::first_run();
        let decision = decide(self, &manifest, &self.parameters.newer_version, &state);
        assert!(
            decision.proceeds(),
            "CONTROL: a pristine newer offer must PROCEED, got {decision:?}"
        );
        assert_eq!(
            manifest.sequence(),
            self.parameters.control_sequence,
            "CONTROL: the control manifest must carry the sequence the driver asked for"
        );
        manifest
    }
}

fn control_asset() -> String {
    format!("accepted{RELEASE_MANIFEST_ASSET_SUFFIX}")
}

fn decide(
    corpus: &Corpus,
    manifest: &VerifiedManifest,
    offered: &str,
    state: &FreezeState,
) -> UpdateDecision {
    wcore_cli::self_update::update_trust::decide_update(&UpdateOffer {
        running_version: &corpus.parameters.running_version,
        offered_version: offered,
        manifest: Some(manifest),
        state,
        now_unix: corpus.now(),
        max_manifest_age_secs: DEFAULT_MAX_MANIFEST_AGE_SECS,
    })
}

// ---------------------------------------------------------------------------
// The drill
// ---------------------------------------------------------------------------

/// The link nothing else in the suite covers: bytes from the real CLI, through
/// the real shipped verifier. A schema drift between the minting crate and the
/// shipped one lands here and nowhere else.
#[test]
#[ignore = "driven by .github/scripts/release-manifest-drill.sh with a minted corpus"]
fn a_cli_minted_manifest_verifies_and_installs_under_the_shipped_verifier() {
    let corpus = Corpus::load();
    let verifier = corpus.verifier("trust-root.json");
    let manifest = corpus.control(&verifier);

    assert_eq!(
        manifest.signing_key_id(),
        "release-acceptance-key",
        "the driver signs with the key id `release.yml` derives from the bundled trust root"
    );
    assert_eq!(manifest.version_string(), corpus.parameters.newer_version);

    // The filename the release publishes is the one the updater scans for.
    // A near-miss here is the silent failure mode this drill exists for.
    assert!(
        control_asset().ends_with(RELEASE_MANIFEST_ASSET_SUFFIX),
        "the corpus asset name must carry the suffix the updater scans for"
    );
}

/// A genuine older release carries genuine provenance and a genuine signature,
/// so nothing before this refuses it.
#[test]
#[ignore = "driven by .github/scripts/release-manifest-drill.sh with a minted corpus"]
fn a_cli_minted_manifest_for_an_older_release_is_refused_as_a_downgrade() {
    let corpus = Corpus::load();
    let verifier = corpus.verifier("trust-root.json");
    corpus.control(&verifier);

    let manifest = verifier
        .verify_manifest_json(
            &corpus.bytes(&format!("rollback{RELEASE_MANIFEST_ASSET_SUFFIX}")),
            corpus.now(),
        )
        .expect("the rollback manifest is correctly signed — that is the point");
    let state = FreezeState::first_run();
    let decision = decide(&corpus, &manifest, &corpus.parameters.older_version, &state);

    assert!(
        matches!(decision, UpdateDecision::RefusedDowngrade { .. }),
        "got {decision:?}"
    );
}

/// A correctly signed but OLD view — a mirror that has stopped moving.
#[test]
#[ignore = "driven by .github/scripts/release-manifest-drill.sh with a minted corpus"]
fn a_cli_minted_manifest_past_its_maximum_age_is_refused_as_a_frozen_view() {
    let corpus = Corpus::load();
    let verifier = corpus.verifier("trust-root.json");
    corpus.control(&verifier);

    let manifest = verifier
        .verify_manifest_json(
            &corpus.bytes(&format!("overage{RELEASE_MANIFEST_ASSET_SUFFIX}")),
            corpus.now(),
        )
        .expect("an over-age manifest is still correctly SIGNED");
    let state = FreezeState::first_run();
    let decision = decide(&corpus, &manifest, &corpus.parameters.newer_version, &state);

    assert!(
        matches!(decision, UpdateDecision::RefusedOverAgeManifest { .. }),
        "got {decision:?}"
    );
}

/// The sequence rule, driven from a real minted sequence rather than a literal:
/// a machine that already installed a higher sequence refuses to go back.
#[test]
#[ignore = "driven by .github/scripts/release-manifest-drill.sh with a minted corpus"]
fn a_cli_minted_manifest_at_or_below_the_high_water_mark_is_refused_as_stale() {
    let corpus = Corpus::load();
    let verifier = corpus.verifier("trust-root.json");
    let control = corpus.control(&verifier);

    let temporary = tempfile::tempdir().expect("temp dir");
    let path = temporary.path().join("release-freeze-state.json");
    let state = FreezeState::record_install_at(&path, control.sequence(), corpus.now())
        .expect("recording an install must succeed");
    assert_eq!(state.highest_sequence, control.sequence());

    // Same manifest, same signature, same everything — only the machine's
    // memory changed. That is what freeze protection is.
    let decision = decide(&corpus, &control, &corpus.parameters.newer_version, &state);
    assert!(
        matches!(decision, UpdateDecision::RefusedStaleSequence { .. }),
        "got {decision:?}"
    );
}

/// A version withdrawn after it was signed. `--revoke-version` on the real
/// `manifest-build` command line.
#[test]
#[ignore = "driven by .github/scripts/release-manifest-drill.sh with a minted corpus"]
fn a_cli_minted_revocation_refuses_the_version_it_names() {
    let corpus = Corpus::load();
    let verifier = corpus.verifier("trust-root.json");
    corpus.control(&verifier);

    let manifest = verifier
        .verify_manifest_json(
            &corpus.bytes(&format!("revoked{RELEASE_MANIFEST_ASSET_SUFFIX}")),
            corpus.now(),
        )
        .expect("a revoking manifest is itself valid");
    let state = FreezeState::first_run();
    let decision = decide(&corpus, &manifest, &corpus.parameters.newer_version, &state);

    match decision {
        UpdateDecision::RefusedRevokedVersion { version, reason } => {
            assert_eq!(version, corpus.parameters.newer_version);
            assert!(!reason.is_empty(), "a revocation must carry its reason");
        }
        other => panic!("got {other:?}"),
    }
}

/// A key retired through the real `trust-root-retire-key` command. Its
/// signatures stay cryptographically valid forever; the trust root is what
/// stops honouring them.
#[test]
#[ignore = "driven by .github/scripts/release-manifest-drill.sh with a minted corpus"]
fn a_manifest_signed_by_a_cli_retired_key_is_refused() {
    let corpus = Corpus::load();

    // Control FIRST, under the un-retired root: the very same bytes verify.
    let live = corpus.verifier("trust-root.json");
    corpus.control(&live);

    let retired = corpus.verifier("trust-root-retired.json");
    let error = retired
        .verify_manifest_json(&corpus.bytes(&control_asset()), corpus.now())
        .expect_err("a retired key must not vouch for an install");
    assert!(
        matches!(error, UpdateTrustError::RetiredKey(_)),
        "got {error:?}"
    );
}

/// Reaching packaging is not reaching acceptance. The packaging key is a real
/// key in the same real trust root, and its signature is cryptographically
/// perfect — the role binding is the whole of the refusal.
#[test]
#[ignore = "driven by .github/scripts/release-manifest-drill.sh with a minted corpus"]
fn a_manifest_signed_by_the_packaging_key_is_refused_on_its_role() {
    let corpus = Corpus::load();
    let verifier = corpus.verifier("trust-root.json");
    corpus.control(&verifier);

    let error = verifier
        .verify_manifest_json(
            &corpus.bytes(&format!("packaging-signed{RELEASE_MANIFEST_ASSET_SUFFIX}")),
            corpus.now(),
        )
        .expect_err("only the release-acceptance role may authorise an install");

    match error {
        UpdateTrustError::RoleMismatch {
            bound, required, ..
        } => {
            assert_eq!(bound, "packaging");
            assert_eq!(required, "release_acceptance");
        }
        other => panic!("got {other:?}"),
    }
}

/// The digest binding, driven through the real signer: the driver mints a valid
/// manifest and then edits ONE byte of its body. Everything else — signature,
/// key, role, sequence — is untouched and correct.
#[test]
#[ignore = "driven by .github/scripts/release-manifest-drill.sh with a minted corpus"]
fn a_cli_minted_manifest_edited_after_signing_is_refused() {
    let corpus = Corpus::load();
    let verifier = corpus.verifier("trust-root.json");
    corpus.control(&verifier);

    let error = verifier
        .verify_manifest_json(
            &corpus.bytes(&format!("tampered{RELEASE_MANIFEST_ASSET_SUFFIX}")),
            corpus.now(),
        )
        .expect_err("a body altered after signing must be refused");
    assert!(
        matches!(
            error,
            UpdateTrustError::BodyDigestMismatch | UpdateTrustError::InvalidSignature
        ),
        "got {error:?}"
    );
}

/// The artifact digests must not be decorative: the archive the updater
/// downloaded has to be one the manifest actually vouches for.
#[test]
#[ignore = "driven by .github/scripts/release-manifest-drill.sh with a minted corpus"]
fn the_cli_minted_manifest_binds_the_real_artifact_digests() {
    let corpus = Corpus::load();
    let verifier = corpus.verifier("trust-root.json");
    let manifest = corpus.control(&verifier);

    // Known-positive: the archive the driver actually packaged is named by the
    // manifest, and the digest this test computes INDEPENDENTLY from the bytes
    // on disk is the digest `manifest-build` recorded.
    let name = archive_name(&corpus);
    let archive = corpus.root.join("artifacts").join(&name);
    let bytes =
        std::fs::read(&archive).unwrap_or_else(|error| panic!("{}: {error}", archive.display()));
    let digest = sha256_hex(&bytes);
    manifest
        .check_archive(&name, &digest, bytes.len() as u64)
        .expect("the manifest must vouch for the archive that was packaged");

    // Known-negative, same invocation: one extra byte is refused. Without this
    // the assertion above would pass against a check that accepts anything.
    let mut altered = bytes.clone();
    altered.push(b'!');
    let error = manifest
        .check_archive(&name, &sha256_hex(&altered), altered.len() as u64)
        .expect_err("an altered archive must not satisfy the manifest");
    assert!(
        matches!(error, UpdateTrustError::ArtifactDigestMismatch { .. }),
        "got {error:?}"
    );

    // And an archive the manifest never named is refused by NAME.
    let error = manifest
        .check_archive(
            "wayland-core-not-in-this-release.tar.gz",
            &digest,
            bytes.len() as u64,
        )
        .expect_err("an unnamed artifact must not satisfy the manifest");
    assert!(
        matches!(error, UpdateTrustError::ArtifactNotInManifest(_)),
        "got {error:?}"
    );
}

fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest as _, Sha256};
    format!("{:x}", Sha256::digest(bytes))
}

fn archive_name(corpus: &Corpus) -> String {
    format!(
        "wayland-core-v{}-x86_64-unknown-linux-gnu.tar.gz",
        corpus.parameters.newer_version
    )
}

/// The corpus itself must be non-trivial. A drill that ran against two files
/// because six `wayland-release` invocations silently failed would otherwise
/// report green.
#[test]
#[ignore = "driven by .github/scripts/release-manifest-drill.sh with a minted corpus"]
fn the_minted_corpus_holds_every_case_the_drill_claims_to_cover() {
    let corpus = Corpus::load();
    let expected = [
        "accepted",
        "rollback",
        "overage",
        "revoked",
        "packaging-signed",
        "tampered",
    ];
    for case in expected {
        let name = format!("{case}{RELEASE_MANIFEST_ASSET_SUFFIX}");
        assert!(
            corpus.root.join(&name).is_file(),
            "the corpus is missing {name}"
        );
    }
    for root in ["trust-root.json", "trust-root-retired.json"] {
        assert!(
            corpus.root.join(root).is_file(),
            "the corpus is missing {root}"
        );
    }
    assert!(
        count_manifests(&corpus.root) >= expected.len(),
        "the corpus holds fewer manifests than the drill covers"
    );
}

fn count_manifests(root: &Path) -> usize {
    std::fs::read_dir(root)
        .expect("corpus must be readable")
        .filter_map(Result::ok)
        .filter(|entry| {
            entry
                .file_name()
                .to_str()
                .is_some_and(|name| name.ends_with(RELEASE_MANIFEST_ASSET_SUFFIX))
        })
        .count()
}
