//! `wayland-core init` — scaffold a `.wayland/` directory in the
//! current project with a starter `config.toml` plus a `WAYLAND.md`
//! template at the project root.
//!
//! v0.7.0 1.B.2: non-interactive by design. Reads `WAYLAND_MODEL`
//! from the environment if set, otherwise writes a placeholder. The
//! command is idempotent — existing files are preserved unless
//! `--force` is passed.

use std::fs;
use std::path::PathBuf;

use clap::Args;

/// Default placeholder model written into `config.toml` when neither
/// `WAYLAND_MODEL` nor `--model` is supplied. Kept here as a constant
/// so a single edit drives the test fixture + the user-facing copy.
pub const PLACEHOLDER_MODEL: &str = "claude-sonnet-4-6";

#[derive(Args, Debug, Clone, Default)]
pub struct InitArgs {
    /// Overwrite any files that already exist. Without `--force` the
    /// init is idempotent: each file is written only when missing,
    /// and a one-line "skipped (exists)" notice goes to stderr.
    #[arg(long)]
    pub force: bool,

    /// Default model to write into the starter `config.toml`. When
    /// omitted, falls back to `$WAYLAND_MODEL` and then to
    /// [`PLACEHOLDER_MODEL`].
    #[arg(long)]
    pub model: Option<String>,

    /// Skip the `WAYLAND.md` template at the project root. The
    /// `.wayland/config.toml` is still written.
    #[arg(long)]
    pub skip_context: bool,

    /// Project root to scaffold. Defaults to the current working
    /// directory. Mostly useful for tests; users almost never set it.
    #[arg(long)]
    pub root: Option<PathBuf>,
}

/// Outcome of a single init run, returned for test assertions + so
/// the CLI can print a tidy summary.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct InitOutcome {
    /// `.wayland/config.toml` was written this run.
    pub wrote_config: bool,
    /// `WAYLAND.md` was written this run.
    pub wrote_context: bool,
    /// Files that were skipped because they already existed (and
    /// `--force` was not set). Paths are relative to the project
    /// root, joined with `/` for cross-platform display.
    pub skipped: Vec<String>,
}

/// Render the starter `config.toml` body. Pulled out so tests can
/// assert against the exact bytes written.
pub fn render_config_toml(model: &str) -> String {
    format!(
        "# Wayland-Core project config.\n\
         # v0.7.0 1.B.2: generated by `wayland-core init`. Edit freely;\n\
         # subsequent `init` runs preserve this file unless --force is set.\n\
         \n\
         model = \"{model}\"\n\
         \n\
         [memory]\n\
         # Persistent memory + skill telemetry sink (M3.5).\n\
         # Disable in CI by setting WAYLAND_MEMORY=0.\n\
         enabled = true\n\
         \n\
         [observability]\n\
         # When true, skill lifecycle events flow to the trace sink even\n\
         # without full memory enabled. Cheap; on by default.\n\
         skills_lifecycle = true\n"
    )
}

/// Render the `WAYLAND.md` template. Project-specific context that
/// the engine auto-detects via 1.C.1's `ProjectContext` scanner.
pub fn render_context_md(project_name: &str) -> String {
    format!(
        "# {project_name}\n\
         \n\
         > Project context auto-loaded by Wayland-Core. The engine\n\
         > walks the working directory up to the filesystem root,\n\
         > picking up the closest WAYLAND.md / AGENTS.md /\n\
         > .wayland/context.md / CLAUDE.md it finds.\n\
         \n\
         ## Overview\n\
         \n\
         _Describe what this project does in 1-2 sentences._\n\
         \n\
         ## Conventions\n\
         \n\
         _List the load-bearing patterns / forbidden moves / commands\n\
         worth pinning. Keep it under 200 lines — long context files\n\
         drown the model._\n\
         \n\
         ## Commands\n\
         \n\
         - Build: `TODO`\n\
         - Test:  `TODO`\n\
         - Lint:  `TODO`\n"
    )
}

/// Run the init scaffolder. Returns an outcome describing which files
/// were written vs. skipped, or an error if a filesystem op failed.
pub fn run(args: InitArgs) -> std::io::Result<InitOutcome> {
    let root: PathBuf = match args.root {
        Some(p) => p,
        None => std::env::current_dir()?,
    };
    let model = args
        .model
        .clone()
        .or_else(|| std::env::var("WAYLAND_MODEL").ok())
        .unwrap_or_else(|| PLACEHOLDER_MODEL.to_string());

    let mut outcome = InitOutcome::default();

    let wayland_dir = root.join(".wayland");
    fs::create_dir_all(&wayland_dir)?;

    let config_path = wayland_dir.join("config.toml");
    if config_path.exists() && !args.force {
        outcome.skipped.push(".wayland/config.toml".to_string());
    } else {
        fs::write(&config_path, render_config_toml(&model))?;
        outcome.wrote_config = true;
    }

    if !args.skip_context {
        let context_path = root.join("WAYLAND.md");
        if context_path.exists() && !args.force {
            outcome.skipped.push("WAYLAND.md".to_string());
        } else {
            let project_name = root
                .file_name()
                .and_then(|s| s.to_str())
                .unwrap_or("project");
            fs::write(&context_path, render_context_md(project_name))?;
            outcome.wrote_context = true;
        }
    }

    Ok(outcome)
}

/// Print a tidy human-readable summary of an init run. Used by the
/// CLI dispatcher in `main.rs` after calling [`run`].
pub fn print_summary(outcome: &InitOutcome) {
    if outcome.wrote_config {
        eprintln!("wayland-core: wrote .wayland/config.toml");
    }
    if outcome.wrote_context {
        eprintln!("wayland-core: wrote WAYLAND.md");
    }
    for path in &outcome.skipped {
        eprintln!("wayland-core: skipped {path} (already exists; pass --force to overwrite)");
    }
    if !outcome.wrote_config && !outcome.wrote_context && outcome.skipped.is_empty() {
        eprintln!("wayland-core: nothing to do (--skip-context and config exists)");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;
    use tempfile::TempDir;

    fn args_in(dir: &Path) -> InitArgs {
        InitArgs {
            force: false,
            model: None,
            skip_context: false,
            root: Some(dir.to_path_buf()),
        }
    }

    #[test]
    fn fresh_dir_writes_both_files() {
        let tmp = TempDir::new().unwrap();
        let outcome = run(args_in(tmp.path())).unwrap();
        assert!(outcome.wrote_config);
        assert!(outcome.wrote_context);
        assert!(outcome.skipped.is_empty());
        assert!(tmp.path().join(".wayland/config.toml").exists());
        assert!(tmp.path().join("WAYLAND.md").exists());
    }

    #[test]
    fn idempotent_second_run_skips_both() {
        let tmp = TempDir::new().unwrap();
        let _ = run(args_in(tmp.path())).unwrap();
        let outcome = run(args_in(tmp.path())).unwrap();
        assert!(!outcome.wrote_config);
        assert!(!outcome.wrote_context);
        assert_eq!(outcome.skipped.len(), 2);
    }

    #[test]
    fn force_overwrites_existing() {
        let tmp = TempDir::new().unwrap();
        std::fs::create_dir_all(tmp.path().join(".wayland")).unwrap();
        std::fs::write(tmp.path().join(".wayland/config.toml"), "old").unwrap();
        std::fs::write(tmp.path().join("WAYLAND.md"), "old").unwrap();

        let mut args = args_in(tmp.path());
        args.force = true;
        let outcome = run(args).unwrap();
        assert!(outcome.wrote_config);
        assert!(outcome.wrote_context);
        assert!(outcome.skipped.is_empty());

        let body = std::fs::read_to_string(tmp.path().join(".wayland/config.toml")).unwrap();
        assert_ne!(body, "old");
        assert!(body.contains("model ="));
    }

    #[test]
    fn skip_context_suppresses_markdown() {
        let tmp = TempDir::new().unwrap();
        let mut args = args_in(tmp.path());
        args.skip_context = true;
        let outcome = run(args).unwrap();
        assert!(outcome.wrote_config);
        assert!(!outcome.wrote_context);
        assert!(!tmp.path().join("WAYLAND.md").exists());
    }

    #[test]
    fn explicit_model_overrides_env_and_placeholder() {
        let tmp = TempDir::new().unwrap();
        let mut args = args_in(tmp.path());
        args.model = Some("opus-test".to_string());
        run(args).unwrap();
        let body = std::fs::read_to_string(tmp.path().join(".wayland/config.toml")).unwrap();
        assert!(
            body.contains("opus-test"),
            "config did not pick up explicit model: {body}"
        );
    }

    #[test]
    fn placeholder_used_when_no_model_anywhere() {
        // Save + unset WAYLAND_MODEL for this test.
        let saved = std::env::var("WAYLAND_MODEL").ok();
        // SAFETY: tests run single-threaded by default for this assertion.
        unsafe {
            std::env::remove_var("WAYLAND_MODEL");
        }
        let tmp = TempDir::new().unwrap();
        run(args_in(tmp.path())).unwrap();
        let body = std::fs::read_to_string(tmp.path().join(".wayland/config.toml")).unwrap();
        assert!(body.contains(PLACEHOLDER_MODEL));
        if let Some(v) = saved {
            // SAFETY: same.
            unsafe {
                std::env::set_var("WAYLAND_MODEL", v);
            }
        }
    }
}
