#!/usr/bin/env python3
"""Fail when the release board and the blocking list disagree (wayland#1272 c1).

c1 asks that every issue in `check-release-readiness.py`'s blocking list
appears on the board with a named owner, and that the board is UPDATED
WHENEVER THE LIST CHANGES. A board maintained by hand satisfies that on the
day it is written and silently stops satisfying it the next time an issue
lands or a criterion closes -- which is the failure the ticket describes
("an unowned issue is a bug in this ticket").

So the board is generated from the blocking list and then checked against it.
The check fails in BOTH directions: an issue that blocks and is not on the
board, and an issue on the board that no longer blocks. A stale row is not
cosmetic -- it is the board claiming work is outstanding when it is done, and
it is how a board stops being read.

  --write     regenerate the board from the current blocking list
  --offline   structure only; see check-release-readiness.py's own warning
  --self-test prove this gate can fail
"""

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOARD = ROOT / ".planning" / "RELEASE-BOARD.md"
ISSUE_RE = re.compile(r"^  (FerroxLabs/[\w-]+)#(\d+)\s+(.*)$")
ROW_RE = re.compile(r"^\|\s*(FerroxLabs/[\w-]+#\d+)\s*\|\s*([^|]*?)\s*\|\s*(\d+)\s*\|")


def readiness(offline):
    spec = importlib.util.spec_from_file_location(
        "readiness", ROOT / "scripts" / "check-release-readiness.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.run(ROOT, offline=offline)


def blocking(text):
    """(issue -> (title, outstanding_count)) parsed from the readiness report."""
    found, current = {}, None
    # `run()` hands back a list of lines; the self-test drives a plain string.
    lines = text.splitlines() if isinstance(text, str) else list(text)
    for line in lines:
        match = ISSUE_RE.match(line)
        if match:
            current = f"{match.group(1)}#{match.group(2)}"
            found[current] = [match.group(3).strip(), 0]
            continue
        if line.strip().startswith("OUTSTANDING") and current:
            found[current][1] += 1
    return {key: tuple(value) for key, value in found.items()}


def owners_from_ledger(issue):
    """Owners of the UNMET criteria, read from the ledger rather than assigned."""
    repo, number = issue.split("#")
    stem = "wayland-core" if repo.endswith("wayland-core") else "wayland"
    path = ROOT / ".planning" / "ledger" / f"{stem}-{number}.md"
    if not path.is_file():
        return ""
    text = path.read_text(encoding="utf-8", errors="replace")
    owners, state = [], None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("- id:"):
            state = None
        elif stripped.startswith("state:"):
            state = stripped.split(":", 1)[1].strip()
        elif stripped.startswith("owner:") and state not in ("met", "superseded"):
            owner = stripped.split(":", 1)[1].strip().strip('"')
            if owner and owner not in owners:
                owners.append(owner)
    return ", ".join(owners)


def render(found):
    lines = [
        "# Release board — 0.13.14",
        "",
        "GENERATED by `scripts/check-release-board.py`. Do not hand-edit: the",
        "gate regenerates this from `check-release-readiness.py`'s blocking",
        "list and fails when the two disagree, so an edit here is reverted by",
        "the next run rather than believed.",
        "",
        "Owners come from each ledger's `owner:` on its UNMET criteria — the",
        "owner is read, not assigned, so a row cannot claim an owner the",
        "ledger does not.",
        "",
        f"Blocking issues: {len(found)}   "
        f"Outstanding criteria: {sum(count for _, count in found.values())}",
        "",
        "| Issue | Owner | Outstanding | Title |",
        "|---|---|---:|---|",
    ]
    for issue in sorted(found, key=lambda k: (k.split("#")[0], int(k.split("#")[1]))):
        title, count = found[issue]
        owner = owners_from_ledger(issue) or "UNOWNED"
        lines.append(f"| {issue} | {owner} | {count} | {title.replace('|', '/')} |")
    return "\n".join(lines) + "\n"


def board_rows():
    if not BOARD.is_file():
        return {}
    rows = {}
    for line in BOARD.read_text(encoding="utf-8").splitlines():
        match = ROW_RE.match(line)
        if match:
            rows[match.group(1)] = (match.group(2), int(match.group(3)))
    return rows


def self_test():
    sample = ("  FerroxLabs/wayland#1  a title\n"
              "      OUTSTANDING   c1   x\n"
              "      OUTSTANDING   c2   y\n"
              "  FerroxLabs/wayland-core#2  another\n"
              "      OUTSTANDING   c1   z\n")
    parsed = blocking(sample)
    if parsed != {"FerroxLabs/wayland#1": ("a title", 2),
                  "FerroxLabs/wayland-core#2": ("another", 1)}:
        print(f"SELF-TEST FAIL: blocking list misparsed: {parsed}")
        return 1
    if not compare(parsed, {"FerroxLabs/wayland#1": ("core", 2)}):
        print("SELF-TEST FAIL: a board missing an issue was accepted")
        return 1
    if not compare({}, {"FerroxLabs/wayland#1": ("core", 1)}):
        print("SELF-TEST FAIL: a stale board row was accepted")
        return 1
    if not compare(parsed, {"FerroxLabs/wayland#1": ("UNOWNED", 2),
                            "FerroxLabs/wayland-core#2": ("core", 1)}):
        print("SELF-TEST FAIL: an unowned row was accepted")
        return 1
    if compare({"FerroxLabs/wayland#1": ("t", 2)}, {"FerroxLabs/wayland#1": ("core", 2)}):
        print("SELF-TEST FAIL: a correct board was rejected")
        return 1
    print("SELF-TEST OK: missing, stale, unowned rejected; matching accepted")
    return 0


def compare(found, rows):
    """True when there is a PROBLEM. Kept boolean so self_test can drive it."""
    missing = set(found) - set(rows)
    stale = set(rows) - set(found)
    unowned = [issue for issue, (owner, _) in rows.items()
               if not owner or owner == "UNOWNED"]
    drifted = [issue for issue in set(found) & set(rows)
               if found[issue][1] != rows[issue][1]]
    return bool(missing or stale or unowned or drifted)


def main():
    offline = "--offline" in sys.argv
    if "--self-test" in sys.argv:
        return self_test()

    _, out = readiness(offline)
    found = blocking(out)

    if "--write" in sys.argv:
        BOARD.parent.mkdir(parents=True, exist_ok=True)
        BOARD.write_text(render(found), encoding="utf-8")
        print(f"wrote {BOARD.relative_to(ROOT)}: {len(found)} issue(s), "
              f"{sum(c for _, c in found.values())} outstanding criterion(s)")
        return 0

    rows = board_rows()
    missing = sorted(set(found) - set(rows))
    stale = sorted(set(rows) - set(found))
    unowned = sorted(i for i, (o, _) in rows.items() if not o or o == "UNOWNED")
    drifted = sorted(i for i in set(found) & set(rows) if found[i][1] != rows[i][1])

    if not (missing or stale or unowned or drifted):
        print(f"OK: board carries all {len(found)} blocking issue(s), each owned, "
              f"counts current")
        return 0

    print("FAIL: the release board and the blocking list disagree\n")
    for issue in missing:
        print(f"  BLOCKS BUT NOT ON THE BOARD  {issue}")
    for issue in stale:
        print(f"  ON THE BOARD BUT NO LONGER BLOCKS  {issue}")
    for issue in unowned:
        print(f"  NO NAMED OWNER  {issue}")
    for issue in drifted:
        print(f"  OUTSTANDING COUNT MOVED  {issue}: "
              f"board {rows[issue][1]}, actual {found[issue][1]}")
    print("\nRegenerate with: python3 scripts/check-release-board.py --write")
    return 1


if __name__ == "__main__":
    sys.exit(main())
